obj=open("swathi.text","w")
obj.write("rishabh - meerut\n")
obj.write("imtiyaz - delhi\n")
obj.write("nilima - cochin\n")
obj.write("rati - shimla\n")
obj.write("ayishah - delhi\n")
obj.write("raghu - shimla\n")
obj.write("naseer-kanpur\n")
obj.write("karthikeyan - delhi\n")
obj.write("salma - jaipur\n")
obj.write("pankaj - delhi\n")
obj.write("brijesh - delhi\n")
obj.write("govind - delhi\n")
obj.write("puneet - shimla\n")
obj.write("siddhi - delhi\n")
obj.write("suman - jaipur\n")
obj.write("rajeev - shimla\n")
obj.write("mohinder - delhi\n")
obj.write("ajendra - jaipur\n")
obj.write("priyanka - shimla\n")
obj.write("neela - delhi\n")
obj.write("sashi - jaipur\n")
obj.write("sarika - delhi\n")
obj.write("deepti - shimla\n")
obj.write("harshad - delhi\n")
obj.write("trishna - raipur\n")
obj.write("pradeep - jaipur\n")
obj.write("sekhar - delhi\n")
obj.write("nand - delhi\n")
obj.write("eanoop - delhi\n")
obj.write("balwinder - tokyo\n")
obj.close()
